### PR TITLE
Fix processing of date formats containing square brackets

### PR DESCRIPTION
**Pull request by ebullient**
- 🐛 Handle moment formats containing []
- 🚸 Revise setting descriptions

### CODE REVIEW

**Comment by wenlzhang** [comment]
With version 0.6.3, when configured with `[✅:: YYYY-MM-DD]`, the appended text is still without brackets for me, e.g. `✅:: 2022-01-08` is appended.

**Comment by ebullient** [comment]
> With version 0.6.3, when configured with `[✅:: YYYY-MM-DD]`, the appended text is still without brackets for me, e.g. `✅:: 2022-01-08` is appended.

You need to use moment formatting for constant values? The above should be:

`[[✅:: ]YYYY-MM-DD[]]`

**Comment by wenlzhang** [comment]
> I use their escape syntax to construct the reverse regex to undo/remove appended text. Square braces surrounding text that is not part of the date format is key. :)

Thanks for the help! It works now.

**Comment by ebullient** [comment]
I updated the README to clarify, too. ;)

**Pull request merged**
